### ISSUE TITLE
Panicked with 'called `Result::unwrap()` on an `Err` value: Custom("invalid value: integer `4984270261285729579`, expected usize")' after compiling to WebAssembly and running on nodejs

### ISSUE THREAD

**Issue by GouwarPower** [softdevteam/grmtools#277]
OS: Ubuntu 20.04 64 bit

Steps to reproduce bug: 
0) Follow Quickstart guide from grmtools book. 
1) Edit the Cargo.toml in the following way
``` toml
[lib]
crate-type = ["cdylib"]

[build-dependencies]
cfgrammar = "0.11"
lrlex = "0.11"
lrpar = "0.11"

[dependencies]
cfgrammar = "0.11"
lrlex = "0.11"
lrpar = "0.11"
wasm-bindgen = "0.2"
console_error_panic_hook = "*"

```
2) Edit parse function in the following way in `src/lib.rs`
``` rust 
#[wasm_bindgen]
pub fn parse(string: &str) -> u64 { 
    console_error_panic_hook::set_once();
    let lexerdef = calc_l::lexerdef();
    let lexer = lexerdef.lexer(string);
    // Pass the lexer to the parser and lex and parse the input.
    let (res, _) = calc_y::parse(&lexer);
    match res {
        Some(r) => r.unwrap(),
        _ => panic!("Failed to parse expression"),
    }
}
```
3) Compile using `wasm-pack build --target nodejs
4) Link the package to a node project
5) Run the following script using node 
```
const calc = require("calc");
console.log(calc.parse("2 + 3"))
```
My initial conjecture is that there is a cast between u64 and usize somewhere, which does not work with the Wasm architecture.
